version: '3.8'

services:
  # Infrastructure
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: unalone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Services
  api-gateway:
    build: ./services/1-api-gateway
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      AUTH_SERVICE_URL: http://auth-service:5001
      MEETUP_SERVICE_URL: http://meetup-service:5002
      GEOSPATIAL_SERVICE_URL: http://geospatial-service:5003
      CHAT_SERVICE_URL: http://chat-service:5004
    depends_on:
      - auth-service
      - meetup-service
      - geospatial-service
      - chat-service

  auth-service:
    build: ./services/2-auth-service
    ports:
      - "5001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:password@postgres:5432/unalone
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
    depends_on:
      - postgres

  meetup-service:
    build: ./services/3-meetup-service
    ports:
      - "5002:3002"
    environment:
      PORT: 3002
      DATABASE_URL: postgresql://postgres:password@postgres:5432/unalone
      GEOSPATIAL_SERVICE_URL: http://geospatial-service:5003
    depends_on:
      - postgres
      - geospatial-service

  geospatial-service:
    build: ./services/4-geospatial-service
    ports:
      - "5003:3003"
    environment:
      PORT: 3003

  chat-service:
    build: ./services/5-chat-service
    ports:
      - "5004:3004"
    environment:
      PORT: 3004
      MONGODB_URL: mongodb://admin:password@mongodb:27017/unalone?authSource=admin
    depends_on:
      - mongodb

  # Frontend
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:4000
    depends_on:
      - api-gateway

volumes:
  postgres_data:
  mongodb_data: